version: '3.8'

services:
  db:
    build: .
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_git_dev
    ports:
      - "5432:5432"
    volumes:
      - .:/pg_git
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: pg_git_dev
    command: ["./wait-for-db.sh", "make", "test"]

volumes:
  pg_data:
